// src/app/config-template.ts
//
// The starter `marksync.yml` for `marksync init` (GH-15 F-5 — Phase 8.1).
// Exports the template content and a `writeStarterConfig(targetDir)` helper
// that writes a VALID v1 config (it round-trips through `loadConfig` —
// AC-F5-1) into the target directory.
//
// ## Overwrite policy (OQ-TP-1 — resolved at delivery)
//
// `marksync init` REFUSES to overwrite an existing `marksync.yml` (the safest
// MS-0002 default — full init DX is MS-0003 / NG-5). When a config already
// exists, `writeStarterConfig` returns `Result.err(ConfigError)` with a clear
// message and an empty `ajvErrors[]`. The `ConfigError` channel is reused for
// the refusal/write-failure paths so the typed Result contract stays uniform;
// these are operational failures rather than validation failures, but the
// discriminated-union arm is the available typed channel (no separate
// "FileExists" kind exists in MS-0002).
//
// Application tier: imports `domain` only (+ node:fs for the write). The
// starter template is a hand-authored constant; it is structurally valid by
// construction and round-trip-tested in config-template.test.ts (AC-F5-1).

import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ConfigError } from "#domain/errors";
import { Result } from "#domain/result";
import type { Result as ResultType } from "#domain/result";

/**
 * Starter `marksync.yml` content written by `marksync init`. Demonstrates the
 * major v1 fields (targets, sync with granularity: squash, render.mermaid,
 * output, provenance) and round-trips through `loadConfig` (AC-F5-1).
 */
export const STARTER_CONFIG = `# marksync.yml — MarkSync configuration.
# See https://marksync.dev/docs/marksync.yml for the full reference.
#
# Generated by 'marksync init'. Edit the values below for your repository.

# Schema version (v1 is the initial MS-0002 contract).
version: 1

# Corpus root directory (repo-relative, forward slashes).
root: docs/

# Glob patterns selecting markdown files from the Git-tracked tree.
select:
  - docs/**/*.md

# Glob patterns removing matched files from the selected set.
exclude:
  - docs/draft/**

# Intended Confluence page-tree shape: mirror the repo directory structure.
hierarchy: mirror

# Target Confluence spaces keyed by id. MS-0002 ships a single target.
targets:
  default:
    type: confluence
    spaceKey: ENG
    parentPageId: "000000000000000000"

sync:
  # Branches allowed for sync operations (default: ["main"]).
  allowBranches:
    - main
  # Sync history granularity. MS-0002 accepts ONLY squash; commit-by-commit
  # is deferred to a future milestone (ADR-0010 C-5).
  granularity: squash
  # Plan freshness window in minutes (default: 15).
  stalePlanMinutes: 15

render:
  mermaid:
    policy: render
    securityLevel: strict
    htmlLabels: false
    deterministicIds: true

output:
  format: storage
  color: auto

provenance:
  visiblePanel: true
`;

/** Build a ConfigError carrying an operational (non-validation) message. */
function operationalError(path: string, humanMessage: string): ConfigError {
	return { kind: "InvalidConfig", path, ajvErrors: [], humanMessage };
}

/**
 * Write the starter `marksync.yml` into `targetDir`. Returns `Result.ok` on
 * success, or `Result.err(ConfigError)` when:
 *   - a `marksync.yml` already exists in `targetDir` (refuse-to-overwrite —
 *     OQ-TP-1);
 *   - the write fails (permissions / disk).
 *
 * The written config is a valid v1 config and round-trips through `loadConfig`
 * (asserted in config-template.test.ts — AC-F5-1).
 */
export function writeStarterConfig(
	targetDir: string,
): ResultType<void, ConfigError> {
	const configPath = join(targetDir, "marksync.yml");

	if (existsSync(configPath)) {
		return Result.err(
			operationalError(
				configPath,
				`marksync.yml already exists at ${configPath}. 'marksync init' refuses to overwrite an existing config (MS-0002 safety default). Suggested fix: remove or rename the existing file, or edit it directly.`,
			),
		);
	}

	try {
		writeFileSync(configPath, STARTER_CONFIG, "utf-8");
	} catch (e) {
		const msg = e instanceof Error ? e.message : String(e);
		return Result.err(
			operationalError(
				configPath,
				`cannot write ${configPath}: ${msg}. Suggested fix: check directory permissions and that the path is writable.`,
			),
		);
	}

	return Result.ok(undefined);
}
